source 'https://rubygems.org'

gem 'activesupport'
gem 'google-cloud-storage'
gem 'sinatra'

group :development do
  gem 'guard'
  gem 'guard-rspec', require: false
end

group :test do
  gem 'rspec'
end
